import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/themes/theme-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "sonner";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "PaperTrail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ 
  children: React.ReactNode;
}>) {
  return (
       
    <html lang="en" suppressHydrationWarning>
      <link rel="icon" href="/paper-trail-logo.png" type="image/svg+xml" />

      <body className={` font-mono antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
              <NuqsAdapter>{children}
                <Toaster
                position="top-right"
                />
              </NuqsAdapter>
        </ThemeProvider>
      </body>
    </html>
  );
}
