 import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import "./globals.css";
import { Suspense } from "react";
import { Providers } from "./providers/provider";
import { TbLoader3 } from "react-icons/tb";


export const metadata: Metadata = {
  title: "PaperTrail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ 
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <link rel="icon" href="/paper-trail-logo.png" type="image/svg+xml" />

      <body className={` font-mono antialiased`}>
        
        <Suspense fallback={ <div className="h-[95vh] w-full flex items-center justify-center">
              <TbLoader3 size={56} className="animate-spin" />
            </div>}>
        <Providers>
                {children}
        </Providers>
                <Toaster position="top-right"/>
                </Suspense>
                
      </body>
    </html>
  );
}
